default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: course-app_development

test:
  <<: *default
  database: course-app_test

production:
  <<: *default
  database: course-app_production
  username:
  password:
  host: localhost